import React from "react";

const store = {
    region: [
        {name: "Всі області", id: 0, eventKey: 0},
        {name: "Вінницька область", id: 1, eventKey: 1},
        {name: "Волинська область", id: 2, eventKey: 2},
        {name: "Дніпропетровська область", id: 3, eventKey: 3},
        {name: "Донецька область", id: 4, eventKey: 4},
        {name: "Житомирська область", id: 5, eventKey: 5},
        {name: "Закарпатська область", id: 6, eventKey: 6},
        {name: "Запорізька область", id: 7, eventKey: 7},
        {name: "Івано-Франківська область", id: 8, eventKey: 8},
        {name: "Київська область", id: 9, eventKey: 9},
        {name: "Кіровоградська область", id: 10, eventKey: 10},
        {name: "Луганська область", id: 11, eventKey: 11},
        {name: "Львівська область", id: 12, eventKey: 12},
        {name: "Миколаївська область", id: 13, eventKey: 13},
        {name: "Одеська область", id: 14, eventKey: 14},
        {name: "Полтавська область", id: 15, eventKey: 15},
        {name: "Рівненська область", id: 16, eventKey: 16},
        {name: "Сумська область", id: 17, eventKey: 17},
        {name: "Тернопільська область", id: 18, eventKey: 18},
        {name: "Харківська область", id: 19, eventKey: 19},
        {name: "Херсонська область", id: 20, eventKey: 20},
        {name: "Хмельницька область", id: 21, eventKey: 21},
        {name: "Черкаська область", id: 22, eventKey: 22},
        {name: "Чернівецька область", id: 23, eventKey: 23},
        {name: "Чернігівська область", id: 24, eventKey: 24}

    ],
    diocese: [
        {name: "Київська єпархія", id: 0, eventKey: 0},
        {name: "Балтська єпархія", id: 1, eventKey: 1},
        {name: "Бердянська єпархія", id: 2, eventKey: 2},
        {name: "Бориспільська єпархія", id: 3, eventKey: 3},
        {name: "Вінницька єпархія", id: 4, eventKey: 4},
        {name: "Вознесенська єпархія", id: 5, eventKey: 5},
        {name: "Волинська єпархія", id: 6, eventKey: 6},
        {name: "Володимир-Волинська єпархія", id: 7, eventKey: 7},
        {name: "Горлівська єпархія", id: 8, eventKey: 8},
        {name: "Джанкойська єпархія", id: 9, eventKey: 9},
        {name: "Дніпропетровська єпархія", id: 10, eventKey: 10},
        {name: "Донецька єпархія", id: 11, eventKey: 11},
        {name: "Житомирська єпархія", id: 12, eventKey: 12},
        {name: "Запорізька єпархія", id: 13, eventKey: 13},
        {name: "Кіровоградська єпархія", id: 14, eventKey: 14},
        {name: "Кам'янець-Подільська єпархія", id: 15, eventKey: 15},
        {name: "Кам’янська єпархія", id: 16, eventKey: 16},
        {name: "Конотопська єпархія", id: 17, eventKey: 17},
        {name: "Кременчуцька єпархія", id: 18, eventKey: 18},
        {name: "Криворізька єпархія", id: 19, eventKey: 19},
        {name: "Луганська єпархія", id: 20, eventKey: 20},
        {name: "Миколаївська єпархія", id: 21, eventKey: 21},
        {name: "Могилів-Подільська єпархія", id: 22, eventKey: 22},
        {name: "Мукачівська єпархія", id: 23, eventKey: 23},
        {name: "Ніжинська єпархія", id: 25, eventKey: 25},
        {name: "Новокаховська єпархія", id: 26, eventKey: 26},
        {name: "Овруцька єпархія", id: 27, eventKey: 27},
        {name: "Одеська єпархія", id: 28, eventKey: 28},
        {name: "Олександрійська єпархія", id: 29, eventKey: 29},
        {name: "Полтавська  єпархія", id: 30, eventKey: 30},
        {name: "Рівненська  єпархія", id: 31, eventKey: 31},
        {name: "Ровеньківська  єпархія", id: 32, eventKey: 32},
        {name: "Роменська  єпархія", id: 33, eventKey: 33},
        {name: "Сєверодонецька  єпархія", id: 34, eventKey: 34},
        {name: "Сімферопольська  єпархія", id: 35, eventKey: 35},
        {name: "Сарненська  єпархія", id: 36, eventKey: 36},
        {name: "Сумська  єпархія", id: 37, eventKey: 37},
        {name: "Тернопільська  єпархія", id: 38, eventKey: 38},
        {name: "Тульчинська  єпархія", id: 39, eventKey: 39},
        {name: "Феодосійська  єпархія", id: 40, eventKey: 40},
        {name: "Харківська  єпархія", id: 41, eventKey: 41},
        {name: "Херсонська  єпархія", id: 42, eventKey: 42},
        {name: "Хмельницька  єпархія", id: 43, eventKey: 43},
        {name: "Хустська  єпархія", id: 44, eventKey: 44},
        {name: "Черкаська  єпархія", id: 45, eventKey: 45},
        {name: "Чернівецька  єпархія", id: 46, eventKey: 46},
        {name: "Чернігівська  єпархія", id: 47, eventKey: 47},
        {name: "Шепетівська  єпархія", id: 48, eventKey: 48}
    ],
    data: [
        {id: 1, name: 'Gob', value: '2'},
        {id: 2, name: 'Buster', value: '5'},
        {id: 3, name: 'George Michael', value: '4'}
    ]
}

export default store;

